title: 'FRC Team 449: The Blair Robot Project'
default_lang: en
author:
  name: 'Blair Robot'
  email: blair.robot@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'FRC Team 449 is a FIRST robotics team from Montgomery Blair High School.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
