name: Yarn with Gulp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install yarn
      run: |
        npm install --global yarn

    - name: Build user.bak/plugins/form
      run: |
        cd user.bak/plugins/form
        yarn install
        gulp
    - name: Build user.bak/plugins/admin/themes/grav
      run: |
        cd ../admin/themes/grav
        yarn install
        gulp
